name: Dependabot Manager

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  dependabot-manager:
    name: Dependabot Manager
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-dependabot-manager.yml@master
    secrets: inherit

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - dependabot-manager
    if: always()
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-workflow-summary.yml@master

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-workflow-notifier.yml@master
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
