name: GitHub Actions Security

on:
  push:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  github-actions-security:
    name: GitHub Actions Security
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-github-actions-security.yml@master

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - github-actions-security
    if: always()
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-workflow-summary.yml@master

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-workflow-notifier.yml@master
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
